Terra
zhmylove/itmmorgue pull request #71
Opened 2018-04-24 09:46 UTC by zhmylove

2018-04-24 09:47 UTC, zhmylove commented
@ValeriyKr рефакторить, вероятно, будем при мерже terra -> master..?

2018-04-26 01:18 UTC, ValeriyKr requested changes
Бегло проглядел код. Супер!

На данный момент замечания: странная расстановка пробелов местами (не критично), нет проверок возвращаемого значения malloc (критично, снова дебажить SIGSEGV не хочу, стоит добавить).
Кроме того, я перловый код бы не выпиливал. Пусть лежит.

2019-04-10 20:25 UTC, zhmylove commented
*alloc пофикшу следующим коммитом.

2019-04-10 20:27 UTC, zhmylove commented
Для сохранения owner-ов, делаю merge commit

2019-04-10 20:27 UTC, merged